spring.application.name=payment-service


server.port=8082
spring.kafka.bootstrap-servers=localhost:9092


# ? Security (keep as is)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# ? FIXED DESERIALIZER (IMPORTANT)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# ? Consumer settings
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=latest

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
#
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#
#spring.kafka.consumer.properties.spring.json.trusted.packages=*
#spring.kafka.consumer.properties.spring.json.value.default.type=com.example.payment_service.event.OrderEvent