spring.application.name=transaction-service

server.port=8083
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=transaction-group
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
